### ISSUE TITLE
Code For CIFAR&ResNet?

### ISSUE THREAD

**Issue by brave-cattle** [ykwon0407/beta_shapley#1]
Hello! Thank you for your interesting and enlightening work.

Could you release the experimental code using CIFAR100 and ResNet-18 mentioned in the paper?
Since the released code is mainly utilizing numpy and sklearn, adding this part is not simple for me.

**Comment by ykwon0407** [comment]
Hi @brave-cattle, I am really sorry for the very late reply. I am using this repository just to provide key parts of the proposed algorithm. If you are interested in the implementation of ResNet-18, please send me an email! I am happy to share it!
