### ISSUE TITLE
Implementation for regression task

### ISSUE THREAD

**Issue by peiyaoli** [ykwon0407/beta_shapley#2]
Hi, 
thanks for sharing this code.
I want to know whether regression task has been implemented?
Many thanks

**Comment by ykwon0407** [comment]
Hi @peiyaoli, thank you for reaching out. This repo focuses on the classification task, but it would be straightforward to extend to regression tasks as `ShapEngine.py` has a `problem` parameter. You may need to modify `data.py` to load regression datasets.

**Comment by peiyaoli** [comment]
@ykwon0407 Many thanks for the reply. I will try it out.
