### ISSUE TITLE
No License File

### ISSUE THREAD

**Issue by Robdei** [ykwon0407/beta_shapley#3]
There is no open-source license file in this repo. Is there a limitation on who can use this code?

**Comment by Robdei** [comment]
Just curious. I read the paper and this seems very interesting.

**Comment by ykwon0407** [comment]
Hi @Robdei, there is no limitation to use this code. However, I recommend the opendataval [[link]](https://github.com/opendataval/opendataval). BetaShapley is implemented in this [[link]](https://github.com/opendataval/opendataval/blob/main/opendataval/dataval/margcontrib/betashap.py) It provides a better implementation with an easy-to-use comparative environment. You can also check other data valuation/contribution estimation algorithms in that link.

**Comment by Robdei** [comment]
Great! Thank you @ykwon0407!

I love your and James Zou's work.

**Comment by ykwon0407** [comment]
@Robdei  Thanks! Please feel free to let me know if you have any questions :)
